### ISSUE TITLE
Provider produced inconsistent final plan - cty.StringVal("")

### ISSUE THREAD

**Issue by reddy-dilip** [zambien/terraform-provider-apigee#57] opened 2020-01-28 20:11 UTC
Hi There,

**Terraform Version**
Terraform v0.12.20
apigee provider 0.0.21

**Terraform Configuration Files**
Use the examples, but explode a proxy zip into ~/proxy_files

**Expected Behavior**
Create Proxy's,Products,Developers and App's.

**Actual Behavior**
apigee_developer.helloworld_developer: Refreshing state... [id=dfa05cc1-a607-4a63-bedf-6830b4ee1d94]
data.archive_file.bundle: Refreshing state...
apigee_api_proxy.helloworld_proxy: Refreshing state... [id=fb601905-f48e-47af-bafd-2bd1f24cb327]
apigee_api_proxy.helloworld_proxy: Destroying... [id=fb601905-f48e-47af-bafd-2bd1f24cb327]
apigee_developer.helloworld_developer: Destroying... [id=dfa05cc1-a607-4a63-bedf-6830b4ee1d94]
apigee_api_proxy.helloworld_proxy: Destruction complete after 0s
apigee_developer.helloworld_developer: Destruction complete after 0s
apigee_api_proxy.helloworld_proxy: Creating...
apigee_developer.helloworld_developer: Creating...
apigee_api_proxy.helloworld_proxy: Creation complete after 0s [id=3a57c303-679d-4ae4-b043-bfbc99f47093]
apigee_developer.helloworld_developer: Creation complete after 0s [id=df2209ee-c744-4f5f-b632-fc619c5fb906]

Error: Provider produced inconsistent final plan

When expanding the plan for
apigee_api_proxy_deployment.helloworld_proxy_deployment to include new values
learned so far during apply, provider "apigee" produced an invalid new value
for .proxy_name: was cty.StringVal("helloworld-terraformed"), but now
cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for apigee_product.helloworld_product to include new
values learned so far during apply, provider "apigee" produced an invalid new
value for .proxies[0]: was cty.StringVal("helloworld-terraformed"), but now
cty.StringVal("").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Steps to Reproduce**
Ran the hello world code,added proxies under proxies folder.

**Comment by bostrowski13** [comment] 2020-02-26 14:28
Pretty sure this is the same as https://github.com/zambien/terraform-provider-apigee/issues/40

**Comment by zambien** [comment] 2020-03-26 12:54
Closing as this is a duplicate of #40

**Closed by zambien** 2020-03-26 12:54 UTC

**Comment by ZdenT** [comment] 2020-09-04 11:23
I think that's not the same as #40. I have the same issue with Terraform 0.13.1 and apigee provider 0.0.23 #40 should be fixed in this release.
